### ISSUE TITLE
Weird behaviour when using snippets in lua programming

### ISSUE THREAD

**Issue by kmafeni04** [vqns/lite-xl-snippets#4]
[Video](https://imgur.com/ufFtIqT)

Snippets appear but the original text isn't removed

**Comment by vqns** [comment]
That's weird. What version/commit of the editor and the plugin are you using? And where is the snippet sourced from? an lsp server / local config files? Also out of curiosity, could you add the following line in `snippets.lua`, at the top of the `M.execute` function and try to execute a snippet?

```lua
core.log('SNIPPETS PARTIAL: "%s"', partial)
```

**Comment by Guldoman** [comment]
I think this issue was fixed by bdf1f16e784c8ebd148a2060a2186d12a3c8306d, but the manifest in the plugins repo still points to 37a24d0970668e39ef571e607281e61135f7a504, so lpm downloads that.

**Comment by vqns** [comment]
> I think this issue was fixed by [bdf1f16](https://github.com/vqns/lite-xl-snippets/commit/bdf1f16e784c8ebd148a2060a2186d12a3c8306d), but the manifest in the plugins repo still points to [37a24d0](https://github.com/vqns/lite-xl-snippets/commit/37a24d0970668e39ef571e607281e61135f7a504), so lpm downloads that.

That would make sense. Reading through the lsp plugin code, it does indeed sets the selection before calling `execute`. I still have some fixes to commit & then I'll update the manifest in the plugins repo 

@kmafeni04 would you mind upgrading to a more recent commit and confirm whether it does fix the issue?

**Comment by kmafeni04** [comment]
> @kmafeni04 would you mind upgrading to a more recent commit and confirm whether it does fix the issue?

Applied the update, works now
